### ISSUE TITLE
Main MVP

### ISSUE THREAD

**Issue by igooralm192** [igooralm192/ProjetoPOO#51]
## Descrição
> Implement MVP in MainActivity and establish connections between the database.
>
### Tarefas
- [x] MVP classes and interfaces in main package #52 
- [x] Create getCategories functions #53 
- [x] Search filter MVP #74 

**Observações:** 
- Lembre-se de setar a qual **_Project_** e **_Milestone_** esta issue pertencerá.
- Tire proveito dos **_labels_**.
