### ISSUE TITLE
Category MVP

### ISSUE THREAD

**Issue by luisgrappi** [igooralm192/ProjetoPOO#66]
## Descrição
> Implement MVP in CategoryActivity and establish connections between the database.
>
### Tarefas
- [x] MVP classes and interfaces in category package #67 
- [x] Create transition on click subcategories #69 
- [x] On product click action #70 
- [x] Search bar filter in database #71 

**Observações:** 
- Lembre-se de setar a qual **_Project_** e **_Milestone_** esta issue pertencerá.
- Tire proveito dos **_labels_**.
