### ISSUE TITLE
Product MVP

### ISSUE THREAD

**Issue by igooralm192** [igooralm192/ProjetoPOO#88]
## Descrição
> Implement MVP in ProductActivity and establish connections between the database.
>
### Tarefas
- [x] MVP classes and interfaces in product package #89
- [x] Create getProduct functions #90 
- [x] Create addFeedback functions #91 

**Observações:** 
- Lembre-se de setar a qual **_Project_** e **_Milestone_** esta issue pertencerá.
- Tire proveito dos **_labels_**.
